### ISSUE TITLE
KeyError: 'meta'

### ISSUE THREAD

**Issue by abhishekmangudkar** [Isma399/grafana_mail#10]
_Command:_
grafana_mail.py -m **To_Email_ID** -M **Host_IP_with_Port** -G http://**ip-address**:3000 -T **grafana_api_key** -D **dashboard_ID**

_Output:_
Render complete dashboard with UID 1
Traceback (most recent call last):
  File "path to\grafana_mail.py", line 193, in <module>
    headers={"Authorization": "Bearer " + args.api_token}).json()
KeyError: 'meta'

**Please help as soon as possible.**

_Note:_
Generated API key from grafana as Admin priviliges named it dash.

Thank you,,

**Comment by icepicknz** [comment]
Same error for me :/

Render complete dashboard with UID 9
Traceback (most recent call last):
  File "grafana_mail.py", line 210, in <module>
    d = (d[0], dash_json['meta']['slug'])
KeyError: 'meta'

**Comment by lucavechi** [comment]
Hi,

Most probably, the searched dashboard is not being retrieved.

Ensure you pass the correct UID dashboard.
